### ISSUE TITLE
Checking if box 'ubuntu/trusty64' is up to date... ?

### ISSUE THREAD

**Issue by flik** [lcreid/solr-nutch-vagrant#14]
```
bash-3.2# vagrant init 'jadesystems/solr-nutch'; 
`Vagrantfile` already exists in this directory. Remove it before
running `vagrant init`.
bash-3.2# vagrant init 'jadesystems/solr-nutch'; 
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
bash-3.2# vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: There was a problem while downloading the metadata for your box
==> default: to check for updates. This is not an error, since it is usually due
==> default: to temporary network problems. This is just a warning. The problem
==> default: encountered was:
==> default: 
==> default: Could not resolve host: vagrantcloud.com
==> default: 
==> default: If you want to check for box updates, verify your network connection
==> default: is valid and try again.
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
bash-3.2# 
```

**Comment by flik** [comment]
It should fetch box jadesystems/solr-nutch

**Comment by lcreid** [comment]
This box never worked to my satisfaction. It looks like I may have left it in an incomplete state the last time I touched it. I didn't actually finish the Vagrant box, and I should have removed it from vagrantcloud. My sincere apologies.

If you're interested in this work, I'll try to clean up the documentation a bit and make it so at least what's in the repository is usable.

Again, my apologies for leaving this in an incomplete state.

**Comment by lcreid** [comment]
This box never worked to my satisfaction. It looks like I may have left it in an incomplete state the last time I touched it. I've updated the README for the master branch so you can build the box from Github. You'll need to Google for the password for the ubuntu/xenial64 box. I'll archive the project now so others won't have the issue you did. You're welcome to fork, of course.
